// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace NyelvtechBeadandoML.Model
{
    public class ModelInput
    {
        [ColumnName("FORM-3"), LoadColumn(0)]
        public string FORM_m3 { get; set; }


        [ColumnName("LEMMA-3"), LoadColumn(1)]
        public string LEMMA_m3 { get; set; }


        [ColumnName("FORM-2"), LoadColumn(2)]
        public string FORM_m2 { get; set; }


        [ColumnName("LEMMA-2"), LoadColumn(3)]
        public string LEMMA_m2 { get; set; }


        [ColumnName("FORM-1"), LoadColumn(4)]
        public string FORM_m1 { get; set; }


        [ColumnName("LEMMA-1"), LoadColumn(5)]
        public string LEMMA_m1 { get; set; }


        [ColumnName("FORM0"), LoadColumn(6)]
        public string FORM0 { get; set; }


        [ColumnName("LEMMA0"), LoadColumn(7)]
        public string LEMMA0 { get; set; }


        [ColumnName("FORM+1"), LoadColumn(8)]
        public string FORM_p1 { get; set; }


        [ColumnName("LEMMA+1"), LoadColumn(9)]
        public string LEMMA_p1 { get; set; }


        [ColumnName("FORM+2"), LoadColumn(10)]
        public string FORM_p2 { get; set; }


        [ColumnName("LEMMA+2"), LoadColumn(11)]
        public string LEMMA_p2 { get; set; }


        [ColumnName("FORM+3"), LoadColumn(12)]
        public string FORM_p3 { get; set; }


        [ColumnName("LEMMA+3"), LoadColumn(13)]
        public string LEMMA_p3 { get; set; }


        [ColumnName("PARSEME:MWE"), LoadColumn(14)]
        public string PARSEME_MWE { get; set; }


    }
}
