// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace NyelvtechBeadandoML.Model
{
    public class ModelInput
    {
        [ColumnName("ID"), LoadColumn(0)]
        public float ID { get; set; }


        [ColumnName("FORM"), LoadColumn(1)]
        public string FORM { get; set; }


        [ColumnName("LEMMA"), LoadColumn(2)]
        public string LEMMA { get; set; }


        [ColumnName("UPOS"), LoadColumn(3)]
        public string UPOS { get; set; }


        [ColumnName("XPOS"), LoadColumn(4)]
        public string XPOS { get; set; }


        [ColumnName("FEATS"), LoadColumn(5)]
        public string FEATS { get; set; }


        [ColumnName("HEAD"), LoadColumn(6)]
        public float HEAD { get; set; }


        [ColumnName("DEPREL"), LoadColumn(7)]
        public string DEPREL { get; set; }


        [ColumnName("DEPS"), LoadColumn(8)]
        public string DEPS { get; set; }


        [ColumnName("MISC"), LoadColumn(9)]
        public string MISC { get; set; }


        [ColumnName("PARSEME:MWE"), LoadColumn(10)]
        public string PARSEME_MWE { get; set; }


    }
}
